In [6]:
# Scientific number notation
print(1e-3)
print(0.001)
print(0.00_1)
print(7.6019e-04)

0.001
0.001
0.001
0.00076019


In [9]:
def foo():
    return (
        (1,2),
        (3,4)
    )

(a,b),t2 = foo()
print(a)
print(b)
print(t2)


1
2
(3, 4)


In [13]:
import numpy as np

arr2d = np.array([[0,234],[2,255]])
print(arr2d.shape)
arr2d

(2, 2)


array([[  0, 234],
       [  2, 255]])

In [14]:
arr  = arr2d.reshape((2*2,))
print(arr.shape)
arr

(4,)


array([  0, 234,   2, 255])

In [15]:
arr = arr/255
arr

array([0.        , 0.91764706, 0.00784314, 1.        ])