In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df = pd.read_csv('https://github.com/Mitko208/PythonTraining/raw/main/Lecture40/Homework/laptop_price.csv', encoding='latin1')
s = df.loc[:10,'Company']
s

0     Apple
1     Apple
2        HP
3     Apple
4     Apple
5      Acer
6     Apple
7     Apple
8      Asus
9      Acer
10       HP
Name: Company, dtype: object

In [14]:
enc = LabelEncoder()
s_encoded = enc.fit_transform(s)
print(enc.classes_)
print(s_encoded)

tmp_df = pd.DataFrame({
    'Company': s,
    'Company_Encoded': s_encoded,
})
tmp_df

['Acer' 'Apple' 'Asus' 'HP']
[1 1 3 1 1 0 1 1 2 0 3]


Company  Company_Encoded
0    Apple                1
1    Apple                1
2       HP                3
3    Apple                1
4    Apple                1
5     Acer                0
6    Apple                1
7    Apple                1
8     Asus                2
9     Acer                0
10      HP                3

In [15]:
s_2d = s.values.reshape(-1,1)
s_2d.shape

(11, 1)

In [16]:
enc = OneHotEncoder(sparse_output=False)
s_encoded = enc.fit_transform(s_2d)

print(s_encoded)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [21]:
s_encoded = pd.get_dummies(s)
s_encoded.astype(np.int_)
# tmp_df = pd.DataFrame({
#     'Company': s,
#     'Company_Encoded': s_encoded,
# })
# tmp_df

Acer  Apple  Asus  HP
0      0      1     0   0
1      0      1     0   0
2      0      0     0   1
3      0      1     0   0
4      0      1     0   0
5      1      0     0   0
6      0      1     0   0
7      0      1     0   0
8      0      0     1   0
9      1      0     0   0
10     0      0     0   1

In [19]:
s

0     Apple
1     Apple
2        HP
3     Apple
4     Apple
5      Acer
6     Apple
7     Apple
8      Asus
9      Acer
10       HP
Name: Company, dtype: object