In [57]:
import numpy as np
from numpy.random import default_rng

## Data Types

1 byte = 8bit (0-255; -128 - 127) 11111111

In [3]:
ages = np.array([1, 2, 3],dtype=np.ubyte)
ages.dtype

dtype('uint8')

In [10]:
np.array( ['1', '2', 3]str_array = , dtype=np.str_)
print(str_array)
str_array.dtype



['1' '2' '3']


dtype('<U1')

In [22]:
arr = np.array([1,0,3], dtype=np.int8)
arr

# arr_bool = np.bool_(arr)
arr_bool = arr.astype(np.bool_)
arr_bool

array([ True, False,  True])

## Array Attributes

In [23]:
a1 = np.array( ['1', '2', 3], dtype=np.int8 )
a1

array([1, 2, 3], dtype=int8)

In [26]:
a1.shape

(3,)

In [33]:
# create an example array
arr = np.array([ [1,2,3], [4,5,6] ], dtype=np.int8)
print(arr.dtype)
print(arr.size * arr.itemsize)

int8
6


## Array Creation Functions

In [34]:
m = np.array( [
    [1,0,0],
    [0,1,0],
    [0,0,1]
]
)
print(m)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [41]:
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
m = np.eye(3,dtype=np.int8)
print(m)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [44]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [46]:
# create array of evens in [2, 10]
arr = np.arange(2,11,2) # [0,8]
arr


array([ 2,  4,  6,  8, 10])

In [48]:
arr = np.linspace(0,100,num=5, dtype=np.int8)
arr

array([  0,  25,  50,  75, 100], dtype=int8)

In [51]:
# numpy.ones(shape, dtype=None, order='C', *, like=None)[source]

# 3*4 fill with 1
arr = np.ones( (3,4) )
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
A = np.array([1,2,3])
B = np.array([1,2,3])

XX, YY =  np.meshgrid(A,B)
print(XX)
print(YY)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [61]:
# if seed is not 0/None, then the same random generator will be used on each execution
rng = default_rng(seed=1)

arr = rng.integers(1,10, size=5)
arr


array([5, 5, 7, 9, 1])

## Array Indexing and Slicing

In [71]:
l = [1,2,3,4,5,6,7,8]
# list indexing
l[-1]

# list slicing
# l[start:stop:step]
print( l[2:5] ) # 2,3,4
print( l[2:] )
print( l[:5] )

[3, 4, 5]
[3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5]


In [76]:
# on 1D array
a = np.arange(1,10)
print(a)

print(a[3])
print(a[-1])
print(a[2:5] ) # 2,3,4
print(a[2:] )

[1 2 3 4 5 6 7 8 9]
4
9
[3 4 5]
[3 4 5 6 7 8 9]


In [90]:
# on 2D arrays
a = np.arange(1,10).reshape((3,3))
print(a)

print(a[-1,-1])

print( a[1:,0::2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[[4 6]
 [7 9]]
