In [1]:
import numpy as np

# Advanced Indexing


## Boolean indexing

In [3]:
a = np.arange(1,4)
a

array([1, 2, 3])

In [6]:
a[ [True, False, True] ]

array([1, 3])

In [16]:
# TASK: get all even elemetns from array
a = np.arange(1,10)
print(f'a:{a}')

filter = a%2==0
print(filter)

evens = a[ filter ]
print(evens)

a:[1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False]
[2 4 6 8]


In [17]:
evens = a[ a%2==0 ]
print(evens)

[2 4 6 8]


In [26]:
# TASK: Let's have an array of 'scores', and for each score we'll have to assign a category from a predefined list. The goal is to group scores (first column) under 'bad' and 'good' categories, based on the second column.

# Define the scores array
scores = np.array([
    [4, 1],
    [2, 0],
    [3, 0],
    [5, 1],
    [6, 1]
])

# Define the categories
categories = ['bad', 'good']


good_mask = scores[:,1]==1
good_scores = scores[ good_mask, 0 ]
# scores[ [True, False, False, True, True], 0 ]

bad_scores=scores[ scores[:,1]==0, 0 ]

print(good_scores)
print(bad_scores)

[4 5 6]
[2 3]


## Integer array indexig

In [27]:
a = np.arange(1,4)
a

array([1, 2, 3])

In [31]:
a[ [0,1,1,1,1,2,1,0,0] ]

array([1, 2, 2, 2, 2, 3, 2, 1, 1])

In [32]:
# TASK: map list elements to array of indexes
# Given a NumPy array of repeated indexes (e.g., [0, 2, 1, 2, 0, 1, 2]) and a corresponding list of colors (e.g., ['red', 'green', 'blue']), map each index in the array to its respective color.

# let's have a numpy array of repeated values 0, 1 or 2:
# color_indexes = np.array([0, 2, 1, 2, 0, 1, 2])

# # and an array of colors:
# colors = np.array(['red', 'green', 'blue'])

# mapped_colors = colors[color_indexes]
# print(mapped_colors)


['red' 'blue' 'green' 'blue' 'red' 'green' 'blue']
