In [1]:
import numpy as np

# NumPy Operations

In [14]:
a1 = np.arange(1,4)
a2 = a1*10

print(a1)
print(a2)

[1 2 3]
[10 20 30]


In [16]:
a1+a2

array([11, 22, 33])

In [47]:
a1 = np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a1>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [53]:
# TASK: get all even elements from a1, which are >5
# Variant 1
# grater_than_5 = a1[a1>5]
# evens = grater_than_5[ grater_than_5%2==0 ]
# evens


# Varriant 2
# a1[ np.logical_and(a1>5, a1%2==0) ]
a1[ (a1>5) & (a1%2==0) ]



array([6, 8])

In [45]:
a1 = np.array([True, False, True])
a2 = np.logical_not(a1)

print(a1)
print(a2)


np.logical_and(a1, a2)

[ True False  True]
[False  True False]


array([False, False, False])

In [61]:
a1 = np.array([True, False, True])
a1

array([ True, False,  True])

In [62]:
np.any(a1)

True

In [63]:
np.all(a1)

False

In [70]:
a = np.arange(1,7).reshape(2,3)
a = a>3
a


array([[False, False, False],
       [ True,  True,  True]])

In [76]:
np.all(a, axis=0)

array([False, False, False])

## Stats Functions

In [86]:
ages = np.array( [1,2,3,4,5,6,7,8,9,10] )
print(ages)
ages.sort()
print(f'ages sorted: {ages}')

print( np.mean(ages) )
print( np.median(ages) )

# 0 5 10 15 20 25 ... 100

[ 1  2  3  4  5  6  7  8  9 10]
ages sorted: [ 1  2  3  4  5  6  7  8  9 10]
5.5
5.5


In [91]:
# Percentiles: Values below which certain percent of data fall
percentile_0 = np.percentile(ages, 0)
percentile_25 = np.percentile(ages, 25)
percentile_50 = np.percentile(ages, 50)  # same as median
percentile_75 = np.percentile(ages, 75)
percentile_100 = np.percentile(ages, 100)

print("0th Percentile:", percentile_0)
print("25th Percentile:", percentile_25)
print("50th Percentile (Median):", percentile_50)
print("75th Percentile:", percentile_75)
print("100th Percentile:", percentile_100)

0th Percentile: 1.0
25th Percentile: 3.25
50th Percentile (Median): 5.5
75th Percentile: 7.75
100th Percentile: 10.0


In [96]:
data = np.array([2,2,3,4,4,4,4,5,6,6])
data.shape
np.histogram(data, bins=5)

(array([2, 1, 4, 1, 2]), array([2. , 2.8, 3.6, 4.4, 5.2, 6. ]))