In [1]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.shape

(2, 3)

In [7]:
a.size

6

In [12]:
a.reshape( (3,2) )

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [14]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a.reshape((3,3))