In [10]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

## Simple Example

In [11]:
### Prepare data
## Train data
# input: weight (grams) and color score (1-10 scale)
X_train = [
    [150, 7],  # Apple
    [170, 8],  # Apple
    [140, 6],  # Apple
    [300, 4],  # Orange
    [320, 5],  # Orange
    [310, 4]   # Orange
]

# target: 0 for Apple, 1 for Orange
y_train = [0, 0, 0, 1, 1, 1]

## Test data
X_test = [
    [205, 4],  # Should be classified as Apple
    [315, 5]   # Should be classified as Orange
]
y_test = [0, 1]  # Actual labels for the test data

### Scaling features

In [12]:
# min_max_scaler = preprocessing.MinMaxScaler()
# min_max_scaler.fit_transform(X_train)

## Encoding Categorical Variables with Scikit-learn

TODO: Explain with example OneHotEncoder

In [13]:
from sklearn.preprocessing import OneHotEncoder

x = np.array(
    [
        'Male',
        'Male',
        'Male',
        'Female',
        'Female'
    ]
)

X = x.reshape(-1,1)
print(X.shape)

encoder = OneHotEncoder(handle_unknown='ignore')
encoder.fit(X)

print(encoder.categories_)
encoder.transform(X).toarray()



(5, 1)
[array(['Female', 'Male'], dtype='<U6')]


array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

## Handling Missing Values

In [30]:
from sklearn.impute import SimpleImputer

X = np.array(
    [
        ['Male', 30],
        ['Male', 32],
        ['Male', 34],
        ['Female', 54],
        ['Female', 23],
        ['Female', 36],
    ],
    dtype=object
)

X[1,1] = np.NAN;
X[0,0] = np.NAN;
X

array([[nan, 30],
       ['Male', nan],
       ['Male', 34],
       ['Female', 54],
       ['Female', 23],
       ['Female', 36]], dtype=object)

In [31]:
gender_data = X[:,0].reshape(-1,1)
age_data = X[:,1].reshape(-1,1)

print(gender_data)
print(age_data)

[[nan]
 ['Male']
 ['Male']
 ['Female']
 ['Female']
 ['Female']]
[[30]
 [nan]
 [34]
 [54]
 [23]
 [36]]


In [32]:
gender_imputer = SimpleImputer(strategy='most_frequent')
age_inputer = SimpleImputer(strategy='mean')

print(gender_imputer.fit_transform(gender_data))
print(age_inputer.fit_transform(age_data))




[['Female']
 ['Male']
 ['Male']
 ['Female']
 ['Female']
 ['Female']]
[[30. ]
 [35.4]
 [34. ]
 [54. ]
 [23. ]
 [36. ]]


## train_test_split

In [42]:
from sklearn.model_selection import train_test_split



In [43]:
X

array([['nan', '30'],
       ['Male', 'nan'],
       ['Male', '34'],
       ['Female', '54'],
       ['Female', '23']], dtype='<U21')

In [50]:
X_train, X_test = train_test_split(X, train_size=0.75, random_state=42)
print(X_train)
print(X_test)



[['Male' '34']
 ['nan' '30']
 ['Female' '54']]
[['Male' 'nan']
 ['Female' '23']]


In [45]:
5*0.75

3.75